export const CART_STRINGS = {
  header: {
    title: "Giỏ Hàng",
    subtitle: "Tiến hành checkout sản phẩm của bạn",
  },
  empty: {
    title: "Giỏ hàng của bạn đang trống",
    btn: "Mua sắm ngay",
  },
  table: {
    product: "Sản phẩm",
    quantity: "Số lượng",
    total: "Tổng",
    action: "Thao tác",
  },
  invoice: {
    title: "Hóa đơn thanh toán",
    subtotal: "Tạm tính:",
    coupon: "Mã giảm giá",
    couponPlaceholder: "Nhập mã giảm giá",
    couponApplyBtn: "Mã",
    maxDiscount: "(Tối đa)",
    shipping: "Vận chuyển:",
    freeShipping: "Miễn phí toàn quốc",
    discount: "Giảm giá ",
    total: "Tổng cộng:",
    payBtn: "Thanh Toán VNPay",
  },
  recommendations: {
    title: "Khám Phá Thêm",
    description: "Sản phẩm công nghệ cao cấp bạn có thể quan tâm.",
  },
  modal: {
    title: "Thông tin nhận hàng",
    loadingAddress: "Đang tải địa chỉ...",
    fullNameLabel: "Họ và tên người nhận",
    fullNameRequired: "Vui lòng nhập họ tên",
    fullNamePlaceholder: "Nguyễn Văn A",
    phoneLabel: "Số điện thoại",
    phoneRequired: "Vui lòng nhập số điện thoại",
    phoneInvalid: "Số điện thoại không hợp lệ (10-11 số)",
    phonePlaceholder: "09xxxxxxxx",
    provinceLabel: "Tỉnh/Thành phố",
    required: "Bắt buộc",
    provincePlaceholder: "Chọn hoặc gõ tìm kiếm...",
    wardLabel: "Phường/Xã",
    wardPlaceholder: "Chọn Phường/Xã...",
    detailLabel: "Địa chỉ chi tiết",
    detailRequired: "Vui lòng nhập địa chỉ chi tiết",
    detailPlaceholder: "Số nhà, tên đường...",
    saveBtn: "Lưu địa chỉ & Tiếp tục",
    cancelBtn: "Hủy bỏ",
    selectAddress: "Chọn địa chỉ giao hàng:",
    addAddressBtn: "Thêm địa chỉ mới",
    defaultTag: "Mặc định",
    paymentMethodLabel: "Hình thức thanh toán:",
    vnpayLabel: "Thanh toán qua VNPay (ATM/Internet Banking/QR Code)",
    codLabel: "Thanh toán khi nhận hàng (COD)",
    continueVNPay: "Tiếp tục thanh toán VNPay",
    confirmOrder: "Xác nhận đặt hàng",
  },
  messages: {
    updateQtyError: "Không thể cập nhật số lượng",
    removeSuccess: "Đã xóa sản phẩm khỏi giỏ hàng",
    removeError: "Lỗi khi xóa sản phẩm",
    invalidCoupon: "Mã giảm giá không hợp lệ",
    loadAddressError: "Không thể tải danh sách địa chỉ",
    emptyCartError: "Giỏ hàng trống",
    addAddressSuccess: "Đã thêm địa chỉ mới",
    addAddressError: "Lỗi khi thêm địa chỉ",
    loadWardsError: "Không thể tải danh sách Phường/Xã",
    selectAddressError: "Vui lòng chọn địa chỉ giao hàng",
    loginRequired: "Bạn cần đăng nhập để thanh toán",
    codSuccess: "Đơn hàng đã được đặt thành công (COD)!",
    initPaymentError: "Lỗi khởi tạo thanh toán",
  },
};
