export const PRODUCT_STRINGS = {
  realTimeViewer: {
    prefix: "Hiện có",
    suffix: "người đang xem sản phẩm này",
  },
  comparePage: {
    empty: "Chưa có sản phẩm nào để so sánh",
    continueShopping: "Tiếp tục xem sản phẩm",
    backBtn: "Trở về",
    title: "So Sánh Sản Phẩm",
    clearAll: "Xóa tất cả",
    priceLabel: "Giá tiền",
    brandLabel: "Thương hiệu",
    ratingLabel: "Đánh giá",
    specsLabel: "Thông số kỹ thuật",
    addToCart: "Thêm vào giỏ",
  },
  detailPage: {
    notFound: "Sản phẩm không tồn tại hoặc đã bị xóa",
    backToStore: "Quay lại cửa hàng",
    loginToReview: "Vui lòng đăng nhập để gửi đánh giá",
    addCartError: "Không thể thêm sản phẩm vào giỏ hàng",
    addToCart: "Thêm Vào Giỏ",
    specsTitle: "Thông số kỹ thuật",
    descriptionTitle: "Mô tả sản phẩm",
    customerReviewsTitle: "Đánh giá từ khách hàng",
    yourReviewTitle: "Nhận xét của bạn",
    submitReviewBtn: "Gửi đánh giá",
    reviewPlaceholder: "Viết nhận xét...",
    deleteReviewBtn: "Xóa đánh giá",
    comparing: "Đang so sánh",
    compareBtn: "So sánh",
    shareBtn: "Chia sẻ",
    buyNowBtn: "Mua ngay",
    warrantyTitle: "Chính sách mua hàng",
    warrantyItem1: "Bảo hành chính hãng 12-36 tháng",
    warrantyItem2: "1 đổi 1 trong 30 ngày nếu lỗi NSX",
    warrantyItem3: "Miễn phí giao hàng toàn quốc",
    reviewSubmitSuccess: "Gửi đánh giá thành công!",
    reviewSubmitError: "Gửi đánh giá thất bại",
    reviewDeleteSuccess: "Xóa đánh giá thành công",
    reviewDeleteError: "Xóa thất bại",
  },
  productsPage: {
    title: "Tất cả sản phẩm",
    filterTitle: "Bộ lọc sản phẩm",
    brandLabel: "Thương hiệu",
    categoryLabel: "Danh mục",
    priceRangeLabel: "Khoảng giá",
    emptyResult: "Không tìm thấy sản phẩm nào phù hợp với bộ lọc.",
    loading: "Đang tải dữ liệu sản phẩm...",
  },
  searchPage: {
    titlePrefix: "Kết quả tìm kiếm cho",
    filterTitle: "Bộ lọc kết quả",
    brandLabel: "Thương hiệu",
    categoryLabel: "Danh mục",
    priceRangeLabel: "Khoảng giá",
    emptyResult: "Không tìm thấy kết quả nào phù hợp với từ khóa",
    loading: "Đang tìm kiếm sản phẩm...",
  },
};
