export const COMMON_STRINGS = {
  personalizedRecommendations: {
    defaultTitle: "Dành Riêng Cho Bạn",
    defaultDescription: "Dựa trên sở thích và lịch sử xem sản phẩm của bạn.",
    loadingTip: "Đang chuẩn bị gợi ý...",
  },
  compareBar: {
    compareNow: "So Sánh Ngay",
    clearAll: "Xóa tất cả",
  },
  productCard: {
    loginRequired: "Vui lòng đăng nhập để thực hiện",
    addCartError: "Không thể thêm sản phẩm vào giỏ hàng",
    off: "OFF",
    removeFromCompare: "Xóa khỏi so sánh",
    addToCompare: "So sánh sản phẩm",
    bestSeller: "BÁN CHẠY",
    defaultBrand: "TECH",
    addToCart: "Thêm Vào Giỏ",
    viewDetails: "Xem Chi Tiết",
  },
  chatWidget: {
    initialMessage: "Xin chào! Tôi là NovaBot. Tôi có thể giúp gì cho bạn hôm nay?",
    defaultQuestions: [
      "Tech Nova là gì?",
      "Làm sao để đặt hàng?",
      "Chính sách bảo hành?",
      "Phương thức thanh toán?",
      "Liên hệ hỗ trợ?",
    ],
    botFallbackResponse: "Tôi chưa biết câu trả lời này. Đã gửi yêu cầu tới Admin, bạn chờ một chút nhé!",
    handoffWaitingResponse: "Đã chuyển yêu cầu tới tư vấn viên. Bạn vui lòng chờ trong giây lát...",
    botTyping: "NovaBot đang gõ...",
    inputPlaceholder: "Nhập tin nhắn...",
    title: "Nova Assistant",
    adminStatusActive: "● Tư vấn viên đang hỗ trợ",
    adminStatusWaiting: "● Đang chờ tư vấn viên...",
    guestDefaultName: "Khách",
    adminLabel: "Tư vấn viên",
    typingText: "typing...",
    editBtn: "Sửa",
    saveEditBtn: "Lưu",
    cancelEditBtn: "Hủy",
    editedLabel: "đã sửa",
    editExpired: "Chỉ được sửa tin trong vòng 24 giờ",
    editFailed: "Không thể thao tác tin nhắn",
    recalledLabel: "Tin nhắn đã được thu hồi",
  },
  offlinePage: {
    title: "Mất kết nối internet",
    subtitle: "Bạn đang ở chế độ ngoại tuyến. Một số tính năng có thể không khả dụng. Vui lòng kiểm tra lại đường truyền.",
    retryBtn: "Thử lại",
  },
};
