export const ADMIN_STRINGS = {
  header: {
    title: "Quản Trị Hệ Thống",
    subPrefix: "Cửa hàng của bạn đang có ",
    subSuffix: " đơn hàng cần theo dõi",
  },
  cards: {
    stock: "KHO HÀNG",
    stockUnit: "Sản phẩm",
    orders: "ĐƠN HÀNG",
    ordersUnit: "Yêu cầu",
    revenue: "DOANH THU THỰC",
  },
  tabs: {
    productsList: "Danh sách sản phẩm",
    addProduct: "Thêm sản phẩm mới",
    ordersManagement: "Quản lý đơn hàng",
    statistics: "Báo cáo & Thống kê",
    chat: "Chat Tư Vấn",
    notifications: "Quản lý thông báo",
    vouchers: "Mã giảm giá",
    reviews: "Kiểm duyệt đánh giá",
    banners: "Quản lý banner",
  },
  modal: {
    titleUpdate: "Cập nhật thông tin sản phẩm",
    titleAdd: "Thêm sản phẩm mới",
    nameLabel: "Tên sản phẩm",
    nameRequired: "Vui lòng nhập tên sản phẩm",
    namePlaceholder: "Nhập tên sản phẩm...",
    brandLabel: "Thương hiệu",
    brandPlaceholder: "Ví dụ: Apple, Sony...",
    priceLabel: "Giá bán gốc (đ)",
    priceRequired: "Nhập giá gốc",
    discountLabel: "Giảm giá (%)",
    discountPriceLabel: "Giá sau giảm:",
    categoryLabel: "Danh mục sản phẩm",
    categoryRequired: "Chọn danh mục",
    stockLabel: "Tồn kho",
    stockRequired: "Nhập số",
    bestSellerLabel: "Bán chạy?",
    yes: "Có",
    no: "Không",
    activeLabel: "Hiển thị?",
    public: "Công khai",
    hidden: "Tạm ẩn",
    imageLabel: "Hình ảnh sản phẩm",
    uploadBtn: "Tải lên",
    urlPlaceholder: "Hoặc dán URL ảnh tại đây",
    moreImagesLabel: "Ảnh bổ sung (URLs cách nhau bởi dấu phẩy)",
    descLabel: "Mô tả ngắn gọn",
    descPlaceholder: "Mô tả tóm tắt về sản phẩm...",
    specsLabel: "Thông số kỹ thuật chi tiết",
    specsHelp: "Định dạng: Tên thông số: Giá trị; (Ví dụ: RAM: 16GB; Chip: M3;)",
    specsPlaceholder: "Màn hình: 6.7 inch; Chip: A17 Pro; Pin: 29 giờ;",
  },
  messages: {
    confirmDeleteProductTitle: "Xác nhận xóa",
    confirmDeleteProductContent: "Bạn có chắc chắn muốn xóa sản phẩm này không?",
    confirmDeleteOrderTitle: "Xóa vĩnh viễn đơn hàng",
    confirmDeleteOrderContent: "Bạn có chắc chắn muốn xóa đơn hàng này khỏi hệ thống? Hành động này không thể hoàn tác.",
    updateProductSuccess: "Cập nhật sản phẩm thành công!",
    createProductSuccess: "Thêm sản phẩm thành công!",
    deleteProductSuccess: "Xóa sản phẩm thành công",
    deleteOrderSuccess: "Đã xóa đơn hàng",
  },
  error: {
    loadDataError: "Lỗi tải dữ liệu quản trị",
    genericError: "Không thể thực hiện yêu cầu này",
    deleteProductError: "Lỗi khi xóa sản phẩm",
    updateOrderError: "Lỗi cập nhật đơn hàng",
    deleteOrderError: "Lỗi khi xóa đơn hàng",
  },
  orderStatus: {
    pending: "Chờ thanh toán",
    paid: "Đã thanh toán",
    shipping: "Đang giao hàng",
    delivered: "Đã giao hàng",
    failed: "Lỗi giao dịch",
    cancelled: "Đã hủy",
  },
};
