export const BANNER_STRINGS = {
  headerTitle: "Quản lý Banners Quảng Cáo",
  headerSubtitle: "Thiết lập các slide banner xuất hiện tại trang chủ trang web",
  addBtn: "Thêm banner mới",
  table: {
    image: "Hình ảnh",
    title: "Tiêu đề",
    link: "Liên kết (Link)",
    order: "Thứ tự",
    status: "Trạng thái",
    actions: "Thao tác",
    noTitle: "Không có tiêu đề",
    active: "Kích hoạt",
    inactive: "Tạm dừng",
  },
  modal: {
    titleAdd: "Tạo banner mới",
    titleUpdate: "Cập nhật banner quảng cáo",
    btnCreate: "Tạo mới",
    btnUpdate: "Cập nhật",
    titleLabel: "Tiêu đề Banner",
    titlePlaceholder: "Ví dụ: Chương trình khuyến mãi hè 2026",
    linkLabel: "Liên kết chuyển hướng khi click (Link URL)",
    linkPlaceholder: "Ví dụ: /products?brand=Apple hoặc https://...",
    orderLabel: "Thứ tự hiển thị",
    orderRequired: "Vui lòng nhập thứ tự",
    statusLabel: "Trạng thái hiển thị",
    statusActive: "Hiển thị (Kích hoạt)",
    statusInactive: "Tạm ẩn (Tạm dừng)",
    imageLabel: "Hình ảnh Banner (Tỷ lệ khuyến nghị 3:1)",
    uploadBtn: "Tải lên",
    urlPlaceholder: "Hoặc dán URL ảnh trực tiếp vào đây...",
  },
  messages: {
    loadError: "Không thể tải danh sách banner",
    imageRequired: "Vui lòng tải lên hoặc nhập URL ảnh banner",
    updateSuccess: "Cập nhật banner thành công",
    createSuccess: "Tạo banner mới thành công",
    opError: "Lỗi khi thực hiện thao tác",
    statusSuccess: "Đã cập nhật trạng thái hoạt động",
    statusError: "Thao tác thất bại",
    deleteTitle: "Xóa banner quảng cáo",
    deleteContent: "Bạn có chắc chắn muốn xóa banner này? Tệp tin liên quan trên MinIO cũng sẽ được dọn dẹp. Hành động này không thể hoàn tác.",
    deleteSuccess: "Đã xóa banner",
    deleteError: "Không thể xóa banner",
  },
};
