export const VOUCHER_STRINGS = {
  headerTitle: "Quản lý Chương trình Ưu đãi",
  headerSubtitle: "Tạo và điều chỉnh các mã giảm giá cho khách hàng",
  createBtn: "Tạo mã mới",
  table: {
    code: "Mã Code",
    type: "Loại giảm giá",
    minOrder: "Đơn tối thiểu",
    usage: "Lượt dùng",
    status: "Trạng thái",
    action: "Thao tác",
    active: "Kích hoạt",
    inactive: "Tạm dừng",
    percentPrefix: "Giảm ",
    fixedPrefix: "Giảm ",
    progressLabel: "Tiến độ:",
  },
  modal: {
    titleAdd: "Tạo mã giảm giá mới",
    btnSubmit: "Phát hành",
    codeLabel: "Mã Voucher",
    codeRequired: "Nhập mã code",
    codePlaceholder: "Ví dụ: HELLO2024",
    typeLabel: "Kiểu giảm giá",
    typePercent: "Theo phần trăm (%)",
    typeFixed: "Cố định (đ)",
    valueLabel: "Giá trị giảm",
    valueRequired: "Nhập giá trị",
    minOrderLabel: "Giá trị đơn tối thiểu",
    minOrderRequired: "Nhập giá trị",
    usageLimitLabel: "Tổng lượt sử dụng",
    expiresLabel: "Ngày hết hạn",
  },
  messages: {
    loadError: "Không thể tải danh sách mã giảm giá",
    statusSuccess: "Đã cập nhật trạng thái",
    statusError: "Thao tác thất bại",
    deleteTitle: "Xóa mã giảm giá",
    deleteContent: "Bạn có chắc chắn muốn xóa mã này? Hành động này không thể hoàn tác.",
    deleteSuccess: "Đã xóa mã giảm giá",
    deleteError: "Không thể xóa mã giảm giá",
    createSuccess: "Tạo mã giảm giá thành công",
    createError: "Lỗi khi tạo mã",
  },
};
