export const PROFILE_STRINGS = {
  accountMy: "TÀI KHOẢN CỦA TÔI",
  profileTitle: "Hồ Sơ Cá Nhân",
  labelUsername: "Tên đăng nhập",
  labelRole: "Vai trò",
  labelJoinedDate: "Ngày tham gia",
  roleAdmin: "Quản trị viên",
  roleUser: "Người dùng",
  changeAvatarBtn: "Thay ảnh đại diện",
  tabProfile: "Thông tin cá nhân",
  tabPassword: "Đổi mật khẩu",
  inputFullName: "Tên đầy đủ",
  inputEmail: "Email",
  inputPhone: "Số điện thoại",
  inputCurrentPassword: "Mật khẩu hiện tại",
  inputNewPassword: "Mật khẩu mới",
  inputConfirmPassword: "Xác nhận mật khẩu mới",
  submitSaveProfile: "Lưu thay đổi",
  submitChangePassword: "Cập nhật mật khẩu",
  errLoadProfile: "Không thể tải thông tin hồ sơ",
  errPasswordMismatch: "Mật khẩu xác nhận không khớp",
  successUpdateProfile: "Cập nhật hồ sơ thành công",
  successChangePassword: "Đổi mật khẩu thành công",
  successAvatar: "Cập nhật ảnh đại diện thành công",
  errAvatar: "Tải ảnh lên thất bại",
  validation: {
    fullNameRequired: "Vui lòng nhập họ tên",
    emailRequired: "Vui lòng nhập email",
    emailInvalid: "Email không hợp lệ",
    phoneInvalid: "Số điện thoại không hợp lệ",
    currentPasswordRequired: "Vui lòng nhập mật khẩu hiện tại",
    newPasswordRequired: "Vui lòng nhập mật khẩu mới",
    newPasswordMinLen: "Mật khẩu phải có ít nhất 6 ký tự",
    confirmPasswordRequired: "Vui lòng xác nhận mật khẩu",
  },
  placeholders: {
    fullName: "Nguyễn Văn A",
    email: "example@email.com",
    phone: "0901234567",
    currentPassword: "Nhập mật khẩu hiện tại",
    newPassword: "Tối thiểu 6 ký tự",
    confirmPassword: "Nhập lại mật khẩu mới",
  },
};
