export const LAYOUT_STRINGS = {
  footer: {
    copyright: "Tech Nova Full Stack ©2026 Crafted with Passion by Antigravity Team",
  },
  navbar: {
    home: "Trang Chủ",
    products: "Sản Phẩm",
    wishlist: "Yêu Thích",
    profile: "Hồ sơ cá nhân",
    wishlistList: "Danh sách yêu thích",
    myOrders: "Đơn hàng của tôi",
    adminSystem: "Quản trị hệ thống",
    logout: "Đăng xuất",
    notifications: "Thông báo",
    markAllRead: "Đánh dấu tất cả đã đọc",
    noNotifications: "Không có thông báo nào",
    suggestionsForYou: "GỢI Ý CHO BẠN",
    resultsFor: 'KẾT QUẢ CHO "{query}"',
    viewAllResultsFor: 'Xem tất cả kết quả cho "{query}"',
    logoText: "TECH NOVA",
    searchPlaceholder: "Tìm kiếm sản phẩm...",
    notFound: "Không tìm thấy",
    switchToLight: "Chuyển sang giao diện sáng",
    switchToDark: "Chuyển sang giao diện tối",
    supportMessages: "Tin nhắn hỗ trợ",
    cart: "Giỏ hàng",
    login: "Đăng Nhập",
    register: "Đăng Ký",
  },
};
