# Cấu hình kết nối cơ sở dữ liệu MySQL
# Sử dụng mysql-connector-j cho tương thích với Spring Boot 3
spring.datasource.url=jdbc:mysql://localhost:3306/website_application?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ngocminh2609

# Hibernate cấu hình
# Đặt ddl-auto là 'none' vì dự án yêu cầu quản lý cơ sở dữ liệu thủ công qua script SQL riêng
# Việc này đảm bảo Hibernate không tự ý thay đổi cấu trúc bảng, giữ an toàn cho dữ liệu thực tế
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Port mặc định cho ứng dụng
server.port=8080
